export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    headline: 'History of the Community:',
    description: 'LGBTQ is an acronym meaning lesbian, gay, bisexual, transgender and queer or questioning. The term sometimes is extended to LGBTQIA, to include intersex and asexual groups. Queer is an umbrella term for non-straight people; intersex refers to those whose sex is not clearly defined because of genetic, hormonal, or biological differences; and asexual describes those who don’t experience sexual attraction. With the first documenteed gay rights organization, known as The Society for Human Rights, being documented in 1924, the community has grown in members and activists are still working harder than ever to ensure equality amongst all of their members. Most recently, there has been success in legalizing Gay marriage as well as allowing transgender Americans to join the military.',
    buttonLabel: 'Resumé',
    imgStart: false,
    img: require('../../images/pride.jpg').default,
    alt: 'prideIcon',
    dark: true,
    primary: true,
    darkText: true,
}

export const homeObjTwo = {
    id: 'experience',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'contactMe',
    lightBg: false,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'On limited Transactions',
    description: 'Get acceess to something without getting charged any fees',
    buttonLabel: 'Get started',
    imgStart: false,
    img: require('../../images/svg-1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: true,
}